### ISSUE TITLE
Doxity fails with import '@digix/npm_packaged_contract/contract/Contract.sol'

### ISSUE THREAD

**Issue by tymat** [DigixGlobal/doxity#11]
```
$ doxity build
solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc contracts/*
""contracts/test"" is not a valid file. Skipping
Warning: This is a pre-release compiler version, please do not use it in production.
contracts/User.sol:30:1: Error: Source "@digix/solidity-core-libraries/contracts/MathUtils.sol" not found: File not found.
import "@digix/solidity-core-libraries/contracts/MathUtils.sol";
^--------------------------------------------------------------^
child_process.js:533
    throw err;
    ^

Error: Command failed: solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc contracts/*
""contracts/test"" is not a valid file. Skipping
Warning: This is a pre-release compiler version, please do not use it in production.
contracts/User.sol:30:1: Error: Source "@digix/solidity-core-libraries/contracts/MathUtils.sol" not found: File not found.
import "@digix/solidity-core-libraries/contracts/MathUtils.sol";
^--------------------------------------------------------------^

    at checkExecSyncError (child_process.js:490:13)
    at Object.execSync (child_process.js:530:13)
    at exports.default (/usr/local/lib/node_modules/@digix/doxity/lib/compile/index.js:32:56)
    at Object.exports.default [as build] (/usr/local/lib/node_modules/@digix/doxity/lib/build.js:8:25)
    at Object.wrappedMethods.(anonymous function) [as build] (/usr/local/lib/node_modules/@digix/doxity/lib/index.js:71:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digix/doxity/lib/bin/doxity.js:35:28)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3
```

**Comment by hitchcott** [comment]
This was fixed in the recent truffle upgrade
