### ISSUE TITLE
Solidity filenames must match contract names

### ISSUE THREAD

**Issue by ethernomad** [DigixGlobal/doxity#2]
```
jbrown@akalabeth:~/blobstore$ doxity build
solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc abstract_blobstore.sol  blobstore_flags.sol  blobstore_registry.sol  blobstore.sol
Generating output for 1/4 files...fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/jbrown/blobstore/undefined'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at /usr/lib/node_modules/@digix/doxity/lib/compile/index.js:72:50
    at Array.forEach (native)
    at exports.default (/usr/lib/node_modules/@digix/doxity/lib/compile/index.js:43:26)
    at Object.exports.default [as build] (/usr/lib/node_modules/@digix/doxity/lib/build.js:8:25)
    at Object.wrappedMethods.(anonymous function) [as build] (/usr/lib/node_modules/@digix/doxity/lib/index.js:69:24)
    at Object.<anonymous> (/usr/lib/node_modules/@digix/doxity/lib/bin/doxity.js:35:28)
    at Module._compile (module.js:570:32)
```

**Comment by ethernomad** [comment]
Ah - I think you are assuming that Solidity files use the contract name as the filename.

**Comment by hitchcott** [comment]
Yeah, I've been using a truffle environment so that was an assumption. However, there's no reason that's needed. I'll make an update shortly.

**Comment by ethernomad** [comment]
Tried the latest version, but still have the same problem:
```
solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc contracts/*
Generating output for 1/4 files...undefined
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/jbrown/solidity-apis/undefined'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at /usr/lib/node_modules/@digix/doxity/lib/compile/index.js:74:50
    at Array.forEach (native)
    at exports.default (/usr/lib/node_modules/@digix/doxity/lib/compile/index.js:43:26)
    at Object.exports.default [as build] (/usr/lib/node_modules/@digix/doxity/lib/build.js:8:25)
    at Object.wrappedMethods.(anonymous function) [as build] (/usr/lib/node_modules/@digix/doxity/lib/index.js:69:24)
    at Object.<anonymous> (/usr/lib/node_modules/@digix/doxity/lib/bin/doxity.js:35:28)
    at Module._compile (module.js:570:32)
```

**Comment by hitchcott** [comment]
Hmm, strange. Annoying showstopper, but I can't reproduce it. 

Do you have a repo I can try to reproduce?

**Comment by ethernomad** [comment]
This is the repo: https://github.com/link-blockchain/blobstore

**Comment by ethernomad** [comment]
Okay it's working now.
