### ISSUE TITLE
This tool doesn't seems to work on Linux at the moment

### ISSUE THREAD

**Issue by caa1982** [DigixGlobal/doxity#21]
I would love to be able to use this tool but unfortunatly it seems to not be working on Ubuntu at the moment.

**npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar**
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

Node: 9.0
Linux: lubuntu 
NPM: 5.5.1

**Comment by lsaether** [comment]
Wondering if there is a work around for this?

**Comment by Vourhey** [comment]
I'm trying to build a documentation, but it fails

/home/vadim/Projects/core/node_modules/@digix/doxity/lib/compile/index.js:12
    throw new Error('Output directory ' + output + ' not found, are you in the right directory?');
    ^

Error: Output directory /home/vadim/Projects/core/scripts/doxity/pages/docs not found, are you in the right directory?
    at exports.default (/home/vadim/Projects/core/node_modules/@digix/doxity/lib/compile/index.js:12:11)
    at Object.exports.default [as build] (/home/vadim/Projects/core/node_modules/@digix/doxity/lib/build.js:8:25)
    at Object.wrappedMethods.(anonymous function) [as build] (/home/vadim/Projects/core/node_modules/@digix/doxity/lib/index.js:71:24)
    at Object.<anonymous> (/home/vadim/Projects/core/node_modules/@digix/doxity/lib/bin/doxity.js:35:28)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

Kubuntu 16.04
How can I specify the directory?

**Comment by Vourhey** [comment]
Any suggestions? It seems to be a useful tool, but it doesn't work. I have this error 
npm ERR! missing script: build
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vadim/.npm/_logs/2017-11-27T14_03_15_940Z-debug.log

It's caused by publish.js file here:
```
 var cwd = process.env.PWD + '/' + target;
  var outputFolder = cwd + '/public';
  var destFolder = process.env.PWD + '/' + out;
  (0, _helpers.clearDirectory)(destFolder).then(function () {
    var runDev = _child_process2.default.spawn('npm', ['run', 'build'], { cwd: cwd, env: process.env });
    runDev.stdout.pipe(process.stdout);
    runDev.stderr.pipe(process.stderr);
    runDev.on('close', function () {
      _fs2.default.renameSync(outputFolder, destFolder);
      process.stdout.write('Published Documentation to ' + destFolder + '\n');
      process.exit();
    });
  });
```

**Comment by RyanHendricks** [comment]
I don't know much about react and thus was also unable to find a fix for this but I was able to hack together a template to use the project via a git clone method if that is any help to anyone. https://github.com/RyanHendricks/doxity-simpleton
note: this is working on Arch Linux but I haven't tested on Windows or Mac at this time.
