### ISSUE TITLE
can't build project

### ISSUE THREAD

**Issue by klivin** [DigixGlobal/doxity#25]
I have an existing solidity project that I can't gen comments and api for.   Followed directions and this is what I got:

>doxity init

Getting https://github.com/DigixGlobal/doxity-gatsby-starter-project/archive/a4886b7a7a04c018ac04fed3125d7d4785e74bed.tar.gz...
⣟ Setting up doxity project with npm install. This may take a while...npm WARN layer1@1.0.0 No description

up to date in 0.099s
Doxity is initialized! Now run `doxity build`

>doxity build

/usr/local/lib/node_modules/@digix/doxity/lib/compile/index.js:12
    throw new Error('Output directory ' + output + ' not found, are you in the right directory?');
    ^

Error: Output directory /Users/kevin/Desktop/BlockChain/layer1/blockchain/scripts/doxity/pages/docs not found, are you in the right directory?
    at exports.default (/usr/local/lib/node_modules/@digix/doxity/lib/compile/index.js:12:11)
    at Object.exports.default [as build] (/usr/local/lib/node_modules/@digix/doxity/lib/build.js:8:25)
    at Object.wrappedMethods.(anonymous function) [as build] (/usr/local/lib/node_modules/@digix/doxity/lib/index.js:71:24)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digix/doxity/lib/bin/doxity.js:35:28)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Function.Module.runMain (module.js:701:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:618:3

**Comment by ejossev** [comment]
Same issue here...

**Comment by RyanHendricks** [comment]
There's some functional versions floating around that you could modify to meet the needs of your project.

[https://github.com/ProjectWyvern/wyvern-ethereum  --- as part of a larger repo](https://github.com/ProjectWyvern/wyvern-ethereum)
or 
[Hacked together version that works if you follow the readme](https://github.com/RyanHendricks/doxity-simpleton/)

Hopefully one of these might be helpful as there isn't much in the way of doc generators for Solidity at the moment and doxity having been one of the better ones.

**Comment by LucaGuida** [comment]
I have the exact same issue when I try to build the project with `doxity build`...

`throw new Error('Output directory ' + output + ' not found, are you in the right directory?');`

**Comment by quasisamurai** [comment]
Still running this problem.

**Comment by nickgeoca** [comment]
Same problem here:
```bash
...
Doxity is initialized! Now run `doxity build`
$ doxity build
/home/nickgeoca/.nvm/versions/node/v10.9.0/lib/node_modules/@digix/doxity/lib/compile/index.js:12
    throw new Error('Output directory ' + output + ' not found, are you in the right directory?');
    ^

Error: Output directory /home/nickgeoca/TokenPoll/scripts/doxity/pages/docs not found, are you in the right directory?
```
```
Doxity v0.5.2
npm 6.4.0
Ubuntu 17.04
```

**Comment by roynalnaruto** [comment]
Please pull from the `doxity-latest` branch: https://github.com/DigixGlobal/doxity/tree/doxity-latest

In your solidity project (truffle project or just the .sol contracts)
* `npm init` to create an npm project
* Add this as dependency `"@digix/doxity-solc": "0.6.0"`
* Run `./node_modules/.bin/doxity init`
* Note that the directory structure it creates by default is not correct. So please follow this structure as I have in [this](https://github.com/DigixGlobal/dao-contracts/tree/final-changes) repository. Note that there is a `scripts` directory and a `doxity` directory inside that. This `doxity` directory contents are to be copied from whatever the `doxity init` had generated for you.
* Make sure you modify the `linkPrefix` in `scripts/doxity/config.toml` to your project name (`/dao-contracts` in my case)
* Move to the `scripts/doxity` directory and run `npm install`
* Move back out, and run `./node_modules/.bin/doxity compile`
* `./node_modules/.bin/doxity/publish`
* `cd scripts/doxity && ./node_modules/.bin/gatsby/develop`

You can post any further issues, I will assist. You can follow our [dao-contracts](https://github.com/DigixGlobal/dao-contracts) repository to see how we have done it.

**Comment by dimakaplin** [comment]
I do so, now i have json files of my conracts in doxity/pages/docs, but when i use ./node_modules/.bin/doxity/publish, i become error:
Error: ENOENT: no such file or directory, rename '/home/dimakaplin/work/Token-Factory/scripts/doxity/public' -> '/home/dimakaplin/work/Token-Factory/docs'

if i add public to scripts/doxity, when publish i become:
Published Documentation to /home/dimakaplin/work/Token-Factory/docs

but this folder is empty. How i can slove this.

I do this in truffle project (truffle + webpack unbox), sorry for my bad English(( .

**Comment by sarbogast** [comment]
Seriously, if the latest build fixes the issue, why don't you make a new release and fix that for everybody? This makes absolutely no sense.

**Comment by roynalnaruto** [comment]
@sarbogast Nobody is maintaining this repository at present. But I have published the version I am using here: https://www.npmjs.com/package/@digix/doxity-solc
And mentioned some steps that I used to integrate it with my truffle project [above](https://github.com/DigixGlobal/doxity/issues/25#issuecomment-417222129).

**Comment by sarbogast** [comment]
@roynalnaruto Here is what I get when I follow your instructions above:

```
$ ./node_modules/.bin/doxity compile
dyld: Library not loaded: /usr/lib/system/libsystem_network.dylib
  Referenced from: /nix/store/8gc11rhlknifmhf60lf19k234s5id0g4-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found
(node:32968) UnhandledPromiseRejectionWarning: Error: Command failed: solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc contracts/*
dyld: Library not loaded: /usr/lib/system/libsystem_network.dylib
  Referenced from: /nix/store/8gc11rhlknifmhf60lf19k234s5id0g4-Libsystem-osx-10.11.6/lib/libSystem.B.dylib
  Reason: image not found

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at /Users/sarbogast/dev/confcoin-contracts/node_modules/@digix/doxity-solc/lib/compile/solc.js:40:52
    at new Promise (<anonymous>)
    at exports.default (/Users/sarbogast/dev/confcoin-contracts/node_modules/@digix/doxity-solc/lib/compile/solc.js:11:10)
    at Object.exports.default [as compile] (/Users/sarbogast/dev/confcoin-contracts/node_modules/@digix/doxity-solc/lib/compile/index.js:19:29)
    at Object.wrappedMethods.(anonymous function) [as compile] (/Users/sarbogast/dev/confcoin-contracts/node_modules/@digix/doxity-solc/lib/index.js:71:24)
    at Object.<anonymous> (/Users/sarbogast/dev/confcoin-contracts/node_modules/@digix/doxity-solc/lib/bin/doxity.js:35:28)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
(node:32968) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32968) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

**Comment by roynalnaruto** [comment]
@sarbogast I have never faced this problem, but may be this is an issue with installing NixOS in MacOS Mojave? https://github.com/NixOS/nix/issues/2244

**Comment by zeroXBami** [comment]
Follow your instruction but when i compile i got this error: contract.abi.map is not a function.

> @sarbogast I have never faced this problem, but may be this is an issue with installing NixOS in MacOS Mojave? [NixOS/nix#2244](https://github.com/NixOS/nix/issues/2244)

**Comment by tuler** [comment]
Followed the steps but got the error:

```
(node:34295) UnhandledPromiseRejectionWarning: Error: Command failed: solc --combined-json abi,asm,ast,bin,bin-runtime,clone-bin,devdoc,interface,opcodes,srcmap,srcmap-runtime,userdoc contracts/*
Invalid option to --combined-json: clone-bin
```
