### ISSUE TITLE
build crash: Error: Cannot find module 'config'

### ISSUE THREAD

**Issue by scientistnik** [DigixGlobal/doxity#28]
Сonfig is available! 
Doxity v0.5.2
node v9.11.1
```
$ doxity build
contracts/ICO.sol:10:42: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
        if (this.balance != totalSupply) throw;
                                         ^---^
contracts/ICO.sol:13:5: Warning: No visibility specified. Defaulting to "public".
    function ICO(uint _endOfFundingPeriod ) {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:18:5: Warning: No visibility specified. Defaulting to "public".
    function() {throw;}
    ^-----------------^
contracts/ICO.sol:18:17: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
    function() {throw;}
                ^---^
contracts/ICO.sol:20:5: Warning: No visibility specified. Defaulting to "public".
    function buyMagicBeans() payable checkInvariant() {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:21:39: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
        if (now > endOfFundingPeriod) throw;
                                      ^---^
contracts/ICO.sol:26:5: Warning: No visibility specified. Defaulting to "public".
    function refund() checkInvariant() returns(bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:39:5: Warning: No visibility specified. Defaulting to "public".
    function fundTheProject() returns(bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:1:1: Warning: Source file does not specify required compiler version!Consider adding "pragma solidity ^0.4.21;"
contract ICO {
^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:10:13: Warning: Using contract member "balance" inherited from the address type is deprecated. Convert the contract to "address" type to access the member.
        if (this.balance != totalSupply) throw;
            ^----------^
contracts/ICO.sol:41:29: Warning: Using contract member "balance" inherited from the address type is deprecated. Convert the contract to "address" type to access the member.
            && company.send(this.balance))
                            ^----------^
Generating output for 2 contracts...
  done!

> doxity-gatsby-starter-project@1.0.0 build /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity
> gatsby build --prefix-links

Generating CSS
Generating Static HTML
Failed at generating HTML

/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/gatsby/dist/bin/cli.js:52
      throw err;
      ^
Error: Error: Cannot find module 'config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at requireLike (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/require-like/lib/require-like.js:15:26)
    at webpackUniversalModuleDefinition (render-page.js:3:28)
    at render-page.js:10:3
    at Script.runInContext (vm.js:74:29)
    at Script.runInNewContext (vm.js:80:15)
    at module.exports (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/eval/eval.js:69:12)
    at Compiler.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/static-site-generator-webpack-plugin/index.js:31:20)
    at Compiler.applyPluginsAsync (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.emitAssets (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compiler.js:226:7)
    at Compiler.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compiler.js:184:10)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.applyPluginsAsync (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/extract-text-webpack-plugin/index.js:309:4)
    at Compilation.applyPluginsAsync (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/extract-text-webpack-plugin/index.js:285:5)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:209:22)
    at ExtractTextPlugin.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/extract-text-webpack-plugin/index.js:237:10)
    at Compilation.applyPluginsAsync (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:525:7)
    at Compiler.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compiler.js:397:15)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/tapable/lib/Tapable.js:103:11
    at Compilation.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:445:10)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:417:12
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at done (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:246:17)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:44:16
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:332:10
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:52:16
    at Object.async.forEachOf.async.eachOf (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:236:30)
    at Object.async.forEach.async.each (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/async/lib/async.js:209:22)
    at Compilation.addModuleDependencies (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:185:8)
    at Compilation.processModuleDependencies (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:170:7)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:320:12
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:123:4
    at Array.forEach (<anonymous>:null:null)
    at callback (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:122:12)
    at Compilation.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/Compilation.js:140:10)
    at NormalModule.<anonymous> (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack/lib/NormalModule.js:115:10)
    at NormalModule.onModuleBuild (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack-core/lib/NormalModuleMixin.js:310:10)
    at nextLoader (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack-core/lib/NormalModuleMixin.js:275:25)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
    at runSyncOrAsync (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack-core/lib/NormalModuleMixin.js:160:12)
    at nextLoader (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack-core/lib/NormalModuleMixin.js:290:3)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/webpack-core/lib/NormalModuleMixin.js:259:5
    at Storage.finished (/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:38:16)
    at /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doxity-gatsby-starter-project@1.0.0 build: `gatsby build --prefix-links`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doxity-gatsby-starter-project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scientistnik/.npm/_logs/2018-04-11T11_01_11_611Z-debug.log
Published Documentation to /home/scientistnik/workspace/librebank/tests/doxity-simpleton/docs
```
When I install config: `npm i config`:
```
$ doxity build
contracts/ICO.sol:10:42: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
        if (this.balance != totalSupply) throw;
                                         ^---^
contracts/ICO.sol:13:5: Warning: No visibility specified. Defaulting to "public".
    function ICO(uint _endOfFundingPeriod ) {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:18:5: Warning: No visibility specified. Defaulting to "public".
    function() {throw;}
    ^-----------------^
contracts/ICO.sol:18:17: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
    function() {throw;}
                ^---^
contracts/ICO.sol:20:5: Warning: No visibility specified. Defaulting to "public".
    function buyMagicBeans() payable checkInvariant() {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:21:39: Warning: "throw" is deprecated in favour of "revert()", "require()" and "assert()".
        if (now > endOfFundingPeriod) throw;
                                      ^---^
contracts/ICO.sol:26:5: Warning: No visibility specified. Defaulting to "public".
    function refund() checkInvariant() returns(bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:39:5: Warning: No visibility specified. Defaulting to "public".
    function fundTheProject() returns(bool) {
    ^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:1:1: Warning: Source file does not specify required compiler version!Consider adding "pragma solidity ^0.4.21;"
contract ICO {
^ (Relevant source part starts here and spans across multiple lines).
contracts/ICO.sol:10:13: Warning: Using contract member "balance" inherited from the address type is deprecated. Convert the contract to "address" type to access the member.
        if (this.balance != totalSupply) throw;
            ^----------^
contracts/ICO.sol:41:29: Warning: Using contract member "balance" inherited from the address type is deprecated. Convert the contract to "address" type to access the member.
            && company.send(this.balance))
                            ^----------^
Generating output for 2 contracts...
  done!

> doxity-gatsby-starter-project@1.0.0 build /home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity
> gatsby build --prefix-links

Generating CSS
Generating Static HTML
WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
WARNING: No configurations found in configuration directory:/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
Failed at generating HTML

/home/scientistnik/workspace/librebank/tests/doxity-simpleton/doxity/node_modules/gatsby/dist/bin/cli.js:52
      throw err;
      ^
Error: TypeError: Cannot read property 'linkPrefix' of undefined
    at prefixLink (render-page.js:30048:81)
    at module.exports (render-page.js:25338:42)
    at render-page.js:89:40
    at module.exports (render-page.js:101866:11)
    at Object.<anonymous> (render-page.js:88:2)
    at __webpack_require__ (render-page.js:30:30)
    at Object.assign.i (render-page.js:50:18)
    at render-page.js:53:10
    at webpackUniversalModuleDefinition (render-page.js:3:20)
    at render-page.js:10:3

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doxity-gatsby-starter-project@1.0.0 build: `gatsby build --prefix-links`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doxity-gatsby-starter-project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/scientistnik/.npm/_logs/2018-04-11T11_04_29_561Z-debug.log
Published Documentation to /home/scientistnik/workspace/librebank/tests/doxity-simpleton/docs
```

**Comment by ye5no** [comment]
same issue

**Comment by madjarevicn** [comment]
$ doxity build
doxity ⚠️ Error parsing Contract: AssetManager
⚠️ Error parsing Contract: DigitalPrintImage
⚠️ Error parsing Contract: ERC721
⚠️ Error parsing Contract: ImageToken
⚠️ Error parsing Contract: Marketplace
⚠️ Error parsing Contract: Migrations
⚠️ Error parsing Contract: Ownable
Generating output for 7 contracts...
  done!

> doxity-gatsby-starter-project@1.0.0 build /Users/nikolamadjarevic/Desktop/Decenter/DigitalPrint/scripts/doxity
> gatsby build --prefix-links

Generating CSS
Generating Static HTML
Failed at generating HTML

**/Users/nikolamadjarevic/Desktop/Decenter/DigitalPrint/scripts/doxity/node_modules/gatsby/dist/bin/cli.js:52
      throw err;
      ^**
**Error: TypeError: Cannot read property 'path' of undefined**
    at Index.render (render-page.js:30466:53)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (render-page.js:14804:31)
    at ReactCompositeComponentWrapper._renderValidatedComponent (render-page.js:14827:33)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:14367:31)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:14263:22)
    at Object.mountComponent (render-page.js:7281:36)
    at ReactCompositeComponentWrapper.performInitialMount (render-page.js:14376:35)
    at ReactCompositeComponentWrapper.mountComponent (render-page.js:14263:22)
    at Object.mountComponent (render-page.js:7281:36)
    at render-page.js:19590:37

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! doxity-gatsby-starter-project@1.0.0 build: `gatsby build --prefix-links`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the doxity-gatsby-starter-project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nikolamadjarevic/.npm/_logs/2018-05-11T12_18_58_809Z-debug.log



_## almost same issue_

**Comment by ye5no** [comment]
not same. you have problems at compile stage - there are errors parsing contracts.
try to fix it on compile stage.
try run only `doxity compile`, and if there is no errors run `doxity publish`

**Comment by madjarevicn** [comment]
Actually not. I have warnings at compile stage, but it's compiled successfully.

**Comment by MaxBittker** [comment]
this has to do with gatsby version and config.toml being depricated

**Comment by KatSick** [comment]
have the same problem with gatsby build

**Comment by KatSick** [comment]
fixed with using nodejs 8

**Comment by dmytronasyrov** [comment]
Same issue. Downgraded from Node 11 to Node 8. Thanks @KatSick
