### ISSUE TITLE
doxity init: The "listener" argument must be of type Function. Received type undefined

### ISSUE THREAD

**Issue by 7-of-9** [DigixGlobal/doxity#41]
No ./scripts directory is created, exits immediately with trace below.

Node: v10.16.2
npm: 6.9.0

events.js:55
    throw new errors.ERR_INVALID_ARG_TYPE('listener', 'Function', listener);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "listener" argument must be of type Function. Received type undefined
    at checkListener (events.js:55:11)
    at process.removeListener (events.js:318:7)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digix/doxity/node_modules/truffle-compile/index.js:8:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digix/doxity/lib/compile/solc.js:76:23)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@digix/doxity/lib/compile/index.js:44:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)

**Comment by 7-of-9** [comment]
upgraded to node 13.7.0 (npm 6.13.6) - same error.

**Comment by KimiWu123** [comment]
@7-of-9 , have you solved this issue? We need a tool to generate solidity docs as well.

**Comment by shavidzet** [comment]
it would be nice to have support of typescript or flow types, static type checkers can catch problems earlier

**Comment by ArtemGavr** [comment]
> @7-of-9 , have you solved this issue? We need a tool to generate solidity docs as well.

Did you manage to come up with the solution?

**Comment by brjd** [comment]
I am having the same issue, using truffle and the problem comes from the truffle-compiler code.

**Comment by alexcambose** [comment]
This is still happening.

**Comment by klautern** [comment]
Still happening. Any workaround?

**Comment by ArtemGavr** [comment]
I would recommend to modify your instance

**Comment by AWolfsdorf** [comment]
Hey! I downgrade doxity to ^0.4.0 in the package.json and now its working.
